#공통설정
info:
  application:
    name: ${spring.application.name}
    version: ${spring.application.version}
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
spring:
  application:
    name: api-order
    version: 0.0.1


server:
  port: 8083

---
spring:
  application:
    name: api-order-dev
  profiles: dev
  cloud:
    config:
      name: api-order
      uri: http://localhost:8888
      profile: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: config
    password: config
    virtual-host: /config              

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
      
logging:
  level:
    root: INFO
    com.skcomms.dev.api: DEBUG
    
    
          